<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_user_index' => [['user'], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user'], ['variable', '/', '[^/]++', 'user', true], ['text', '/api']], [], [], []],
    'app_user_createuser' => [[], ['_controller' => 'App\\Controller\\UserController::createUser'], [], [['text', '/api/user']], [], [], []],
];
